apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001  # Change the port number if needed

